apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-v0.1.0
spec:
  entrypoint: hello
  templates:
  - name: hello
    inputs:
      parameters:
      - name: s
    script:
      image: hera-example-project:v0.1.0
      source: '{{inputs.parameters}}'
      args:
      - -m
      - hera.workflows.runner
      - -e
      - hera_example_project.workflow_template:hello
      command:
      - python
  arguments:
    parameters:
    - name: s
      value: world
